== CDI

=== 介绍
CDI，上下文和依赖注入是Java规范，为应用程序提供声明性控制和结构。 KIE可以使用它来自动实例化和绑定东西，而不需要使用编程API。

=== 注解
@KContainer，@KBase和@KSession都支持可选的“name”属性。 CDI通常会在注入时执行“getOrCreate”，所有注入都会为同一批注释接收相同的实例。 “名称”注释强制每个名称的唯一实例，尽管该名称的所有实例都将是identity equals。

==== @KReleaseId
用于将实例绑定到KieModule的特定版本。 如果kie-ci位于类路径上，则会自动解析依赖关系，从远程存储库下载。

==== @KContainer
@KContainer是可选的，因为它可以通过使用@Inject和变量类型推断来检测和添加。

.Injects Classpath KieContainer
    @Inject
    private KieContainer kContainer;

.Injects KieContainer for Dynamic KieModule
    @Inject
    @KReleaseId(groupId = "jar1", artifactId = "art1", version = "1.1")
    private KieContainer kContainer;

.Injects named KieContainer for Dynamic KieModule
    @Inject
    @KContainer(name = "kc1")
    @KReleaseId(groupId = "jar1", artifactId = "art1", version = "1.1")
    private KieContainer kContainer;

=== @KBase
@KBase是可选的，因为它可以通过使用@Inject和变量类型推断来检测和添加。

默认参数（如果给定）映射到value属性，并从kmodule.xml文件中指定KieBase的名称。

.从Classpath KieContainer注入默认的KieBase
    @Inject
    private KieBase kbase;

.从动态KieModule注入默认KieBase
    @Inject
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private KieBase kbase;

.并行版本加载“jar1.KBase1”KieBase
    @Inject
    @KBase("kbase1")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private KieBase kbase1v10;

    @Inject
    @KBase("kbase1")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.1")
    private KieBase kbase1v10;

.使用'name'属性为'jar1.KBase1'KieBase强制新的实例
    @Inject
    @KSession(value="kbase1", name="kb1")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private KieBase kbase1kb1;

    @Inject
    @KSession(value="kbase1", name="kb2")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private KieBase kbase1kb2;

==== KieSession的@KSession
@KSession是可选的，因为它可以通过使用@Inject和变量类型推断来检测和添加。

默认参数（如果给出）映射到value属性，并从kmodule.xml文件指定KieSession的名称

.从Classpath KieContainer注入默认的KieSession
    @Inject
    private KieSession ksession;
    Injects the Default KieSession from a Dynamic KieModule
    @Inject
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private KieSession ksession;

.并行版本加载“jar1.KBase1”KieBase
    @Inject
    @KSession("ksession1")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private KieSession ksessionv10;

    @Inject
    @KSession("ksession1")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.1")
    private KieSession ksessionv11;

.使用'name'属性为'jar1.KBase1'KieSession强制新的实例
    @Inject
    @KSession(value="ksession1", name="ks1")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private KieSession ksession1ks1

    @Inject
    @KSession(value="ksession1", name="ks2")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private KieSession ksession1ks2

==== 用于StatelessKieSession的@KSession
@KSession是可选的，因为它可以通过使用@Inject和变量类型推断来检测和添加。

默认参数（如果给出）映射到value属性，并从kmodule.xml文件指定KieSession的名称。

.从Classpath KieContainer注入默认的StatelessKieSession
    @Inject
    private StatelessKieSession ksession;

.从动态KieModule注入默认的StatelessKieSession
    @Inject
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private StatelessKieSession ksession;

.并行版本加载“jar1.KBase1”KieBase
    @Inject
    @KSession("ksession1")
    @KReleaseId( groupId = "jar1", rtifactId = "art1", version = "1.0")
    private StatelessKieSession ksessionv10;

    @Inject
    @KSession("ksession1")
    @KReleaseId( groupId = "jar1", rtifactId = "art1", version = "1.1")
    private StatelessKieSession ksessionv11;

.使用'name'属性为'jar1.KBase1'StatelessKieSession强制新的实例
    @Inject
    @KSession(value="ksession1", name="ks1")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private StatelessKieSession ksession1ks1

    @Inject
    @KSession(value="ksession1", name="ks2")
    @KReleaseId( groupId = "jar1", artifactId = "art1", version = "1.0")
    private StatelessKieSession ksession1ks2

=== API示例比较
CDI可以将实例注入字段，甚至可以将它们作为参数传递。 在这个例子中使用了字段注入。

.一个名为KieSession的CDI例子
    @Inject
    @KSession("ksession1")
    KieSession kSession;

    public void go(PrintStream out) {
        kSession.setGlobal("out", out);
        kSession.insert(new Message("Dave", "Hello, HAL. Do you read me, HAL?"));
        kSession.fireAllRules();
    }

这是比API方法更少的代码和更多的声明。

.指定KieSession的API等效示例
    public void go(PrintStream out) {
        KieServices ks = KieServices.Factory.get();
        KieContainer kContainer = ks.getKieClasspathContainer();

        KieSession kSession = kContainer.newKieSession("ksession1");
        kSession.setGlobal("out", out);
        kSession.insert(new Message("Dave", "Hello, HAL. Do you read me, HAL?"));
        kSession.fireAllRules();
    }